# Generated by Django 5.0.4 on 2024-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='user',
            new_name='foreignKey',
        ),
    ]
