# Generated by Django 5.0.4 on 2024-05-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_grade_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(verbose_name='Биография '),
        ),
    ]
