# Generated by Django 5.0.4 on 2024-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='foreignKey',
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(verbose_name='задачи '),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название задач'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='book',
            field=models.CharField(max_length=50, verbose_name='Название задачи№'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=50, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
