# Generated by Django 5.0.5 on 2024-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_grade_foreignkey_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
