# Generated by Django 5.0.6 on 2024-05-11 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_visible',
        ),
    ]
