# Generated by Django 5.0.6 on 2024-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_book_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
